# Generated by Django 3.1.6 on 2021-03-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jersey_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
