# Generated by Django 3.1.6 on 2021-03-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0002_user_jersey_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='Jersey_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='jersey_num',
            new_name='jersey_Num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
