# Generated by Django 3.1.6 on 2021-03-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0004_auto_20210310_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jersey_Nm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
