# Generated by Django 3.1.6 on 2021-03-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0005_user_jersey_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='me',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
