# Generated by Django 3.1.6 on 2021-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0006_user_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='me',
        ),
        migrations.AddField(
            model_name='user',
            name='jersey_Size',
            field=models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('Ex-large', 'XL')], default='small', max_length=128),
        ),
    ]
