# Generated by Django 3.1.6 on 2021-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0008_remove_user_jersey_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jersey_Size',
            field=models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('Ex-large', 'XL')], max_length=128),
        ),
    ]
